security:
  http:
    oauth2-paths:
      - /oauth2/authorize/**
      - /oauth2/callback/**
    permit-paths:
      - /oauth/login/google
      - /api-docs/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /ws/**
      - /auth/reissue
    cors:
      allowed-origins: # TODO : 추후 FE로 변경
        - "*"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - Authorization
        - Content-Type
      allow-credentials: true
      max-age: 3600
