jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  expiration:
    access: ${JWT_ACCESS_EXPIRATION_MS}
    refresh: ${JWT_REFRESH_EXPIRATION_MS}

apple:
  client-id: com.flyby.ramble
  service-id: com.flyby.ramble.service
  team-id: ${APPLE_TEAM_ID}
  key-id: ${APPLE_KEY_ID}
  private-key: ${APPLE_PRIVATE_KEY}

x-google-common: &google-common
  provider: google
  authorization-grant-type: authorization_code
  scope:
    - openid
    - email
    - profile
    - https://www.googleapis.com/auth/user.gender.read
    - https://www.googleapis.com/auth/user.birthday.read

spring:
  security:
    oauth2:
      client:
        registration:
          google-web:
            client-id: ${GOOGLE_CLIENT_ID_WEB}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            <<: *google-common
          google-android:
            client-id: ${GOOGLE_CLIENT_ID_ANDROID}
            <<: *google-common
          google-ios:
            client-id: ${GOOGLE_CLIENT_ID_IOS}
            <<: *google-common
          apple:
            provider: apple
            client-id: ${apple.service-id}
            client-secret: dummy                              # Spring 검증 통과용
            client-authentication-method: client_secret_post  # POST body로 전송
            redirect-uri: dummy                               # Spring 검증 통과용
            authorization-grant-type: authorization_code
            scope:
              - openid

        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
            user-name-attribute: sub
