security:
  http:
    domain: ${DOMAIN}
    oauth2-paths:
      - /oauth2/authorize/**
      - /oauth2/callback/**
    permit-paths:
      - /api-docs/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /ws/**
      - /auth/reissue
      - /oauth/**
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}
      allowed-methods: ${ALLOWED_METHODS:GET,POST,PUT,DELETE}
      allowed-headers: ${ALLOWED_HEADERS:Content-Type,Authorization}
      allow-credentials: true
      max-age: 3600
